config/routes.rb
MedicalProject::Application.routes.draw do

  get "patients/index"
  get "patient/index"

  get "doctors/calendar/:id", :to => 'doctors#calendar', :as => 'doctors_calendar'

  get "patients/show/:id", :to => 'patients#show', :as => 'patients_info'

  devise_for :doctors, :controllers => {:doctors => "doctors"}

  resources :patients, :doctors, :meetings

  get "patients/index"

  root 'patients#index'

end

app/models/doctor.rb
class Doctor < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :rememberable, :validatable

	has_many :meetings, foreign_key: :doctor_id
	has_many :patients, :through => :meetings

  validates :name, presence: true, length: { in: 2...15 }
  validates :email, format: { with: Devise.email_regexp,
                              message: :bad_email}
  validates :password, confirmation: true
  validates :password_confirmation,
            format: { with: /\A[a-zA-Z0-9_]*\z/,
            message: :bad_password}

  scope :sorted_descending,-> {order("created_at DESC")}

end

app/models/meeting.rb
class Meeting < ActiveRecord::Base

  belongs_to :doctor
	belongs_to :patient

  validates :doctor_id, numericality: { only_integer: true }
  validates :patient_id, numericality: { only_integer: true }

  validate :time_end_cannot_be_higher_time_start

  def time_end_cannot_be_higher_time_start
    if time_end.present? && time_start.present? && time_end <= time_start
      errors.add(:time_end, :bad_time_start_and_end)
    end
  end

end

app/models/patient.rb
class Patient < ActiveRecord::Base
	has_many :meetings, foreign_key: :patient_id
	has_many :doctors, :through => :meetings

  accepts_nested_attributes_for :doctors
  accepts_nested_attributes_for :meetings, allow_destroy: true

  validates :name, presence: true, length: { in: 2...15 }
  validates :skype, presence: true, length: { in: 2...15 }

  validates :tel, format: { with: /\A[0-9\+]{1}[0-9\-]{3,15}\z/,
                            message: :telephone_bad_format}, length: { in: 5...20 }
  validates :age, numericality: { only_integer: true }, :inclusion => 18..50
  validates :gender, inclusion: { in: %w(М Ж),
                                  message: :not_valid_gender }



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :set_locale

  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end

end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
  before_filter :authenticate_doctor!
  before_action :doctor_find_by_id, only: [:edit, :update, :show, :destroy, :calendar ]

  def index
    @doctors = Doctor.sorted_descending.all
  end

  def new
    @doctor = Doctor.new
  end

  def create
    @doctor = Doctor.new(doctor_params)
    if @doctor.save
      flash[:notice] = t('new_doctor_added', doctor: "#{@doctor.name}")
      redirect_to doctors_path
    else
      render action: 'new'
    end
  end

  def edit
  end

  def update
    if @doctor.update(doctor_params)
      flash[:notice] = t('doctor_edited', doctor: "#{@doctor.name}")
        redirect_to edit_doctor_path
    else
      flash[:notice] = t('doctor_edit_fail')
        render action: 'edit'
    end
  end

  def show
  end

  def calendar
    @meetings = Meeting.where(:doctor_id => params[:id])
  end

  def destroy
    if check_if_doctor_is_last?
      if @doctor.destroy
        flash[:notice] = t('doctor_deleted', doctor: "#{@doctor.name}")
      else
        flash[:notice] = t('doctor_delete_fail', doctor: "#{@doctor.name}")
      end
    else
      flash[:notice] = t('last_doctor', doctor: "#{@doctor.name}")
    end
    redirect_to doctors_path
  end

  private
    def doctor_params
      params[:doctor].permit(:name, :email, :password, :password_confirmation)
    end

    def doctor_find_by_id
      @doctor = Doctor.find(params[:id])
    end

    def check_if_doctor_is_last?
      Doctor.count > 1
    end
end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController
  before_action :meeting_find_by_id, only: [:edit, :update ]

  def edit
    @doctor_name = Doctor.find(@meeting.doctor_id).name
    @patient_name = Patient.find(@meeting.patient_id).name
  end

  def update
    if  @meeting.update(meeting_params)
      flash[:notice] = t('time_set_success')
      redirect_to edit_meeting_path
    else
      flash[:notice] = t('time_set_fail')
      render action: 'edit'
    end
  end

  private
    def meeting_params
      params[:meeting].permit(:doctors_id, :patients_id, :time_start, :time_end)
    end

    def meeting_find_by_id
      @meeting = Meeting.find(params[:id])
    end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :authenticate_doctor!, only: [:show]

  def index
  end

  def new
    @patient = Patient.new
    @doctors = @patient.doctors.build
    @doctors_names_list = Doctor.all
  end

  def create

    @patient = Patient.new(patient_params)
    @doctors_names_list = Doctor.all

    if @patient.valid? && params[:doctors][:id] != ''
      if !check_doctor_id?
        flash[:alert] = t('no_such_doctor_id')
        render action: 'new' and return
      end

      @patient.save

      @meeting = Meeting.new(:doctor_id => params[:doctors][:id], :patient_id => @patient.id)
      if @meeting.save
        flash[:notice] = t('meeting_creation_success')
        redirect_to new_patient_path
      else
        render action: 'new'
      end
    elsif (@patient.valid? && params[:doctors][:id] == '')
      flash[:alert] = t('doctor_blank')
      render action: 'new'
    else
      render action: 'new'
    end
  end

  def show
    @patient = Patient.find(params[:id])
  end

  private
    def patient_params
      params[:patient].permit(:name, :skype, :tel, :age, :gender, :doctors_id)
    end

    def check_doctor_id?
      Doctor.pluck(:id).include?(params[:doctors][:id].to_i)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/doctors/calendar.html.erb
<fieldset class="smallForm" style="margin-right: 15%; margin-left: 15%;">
  <legend class="formLegend"><h4><%= t('doctors_calendar_legend') %></h4></legend>
  <table class="table table-striped">
    <h3><%= t('doctor_label') %></h3>
    <tr>
      <td>
        <%= t('name_header') %>
      </td>
      <td>
        <%= @doctor.name %>
      </td>
    </tr>
    <tr>
      <td>
        <%= t('email_header') %>
      </td>
      <td>
        <%= @doctor.email %>
      </td>
    </tr>
  </table>
  <h3><%= t('meeting_label') %></h3>
  <% if @meetings.any? %>

      <table class="table table-hover">
        <thead>
        <tr>
          <th></th>
          <th><%= t('start_header') %></th>
          <th><%= t('end_header') %></th>
        </tr>
        </thead>

        <tbody>
        <% @meetings.each do |meeting| %>
            <tr>
              <td><%= link_to t('patient_link'), patients_info_path(meeting.patient_id) %></td>
              <td><%= meeting.time_start%></td>
              <td><%= meeting.time_end %></td>

              <td><%= link_to t('set_time_link'), edit_meeting_path(meeting) %></td>

            </tr>
        <% end %>
        </tbody>

        <tr>
          <td colspan="2">
            <%= link_to t('go_back_to_doctors_link'), doctors_path %>
          </td>
        </tr>
      </table>


  <% else %>
      <%= t('no_meetings_message') %>
      <br />
      <%= link_to t('go_back_to_doctors_link'), doctors_path %>
  <% end %>



</fieldset>

app/views/doctors/edit.html.erb
<% if notice %>
    <p id="notice" ><%= notice %></p>
<% end %>

<fieldset class="smallForm">
  <legend class="formLegend"><h4><%= t('edit_doctor_legend') %></h4></legend>

  <% if @doctor.errors.any? %>
      <div id="error_explanation" >
        <h4><%= pluralize(@doctor.errors.count, "error" ) %>
          Was found during validation, please fix them to continue:</h4>
        <ul>
          <% @doctor.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
  <% end %>

  <%= simple_form_for @doctor , :html => { :class => 'form-horizontal' } do |f| %>
      <%= f.input :name, label: t('name_header') %>
      <%= f.input :email, label: t('email_header')  %>
      <br />
      <center>
        <%= f.button :submit, t('submit_edit_doctor') %> &nbsp&nbsp&nbsp <%= link_to t('go_back_to_doctors_link'), doctors_path %>
      </center>

  <% end %>



</fieldset>

app/views/doctors/index.html.erb
<% if notice %>
    <p id="notice" ><%= notice %></p>
<% end %>

<h2><%= t('doctors_list') %></h2>

<% if @doctors.any? %>

    <table class="table table-hover">
      <thead>
      <tr>
        <th><%= t('name_header') %></th>
        <th><%= t('email_header') %> </th>
      </tr>
      </thead>

      <tbody>
      <% @doctors.each do |doctor| %>
          <tr>
            <td><%= doctor.name %></td>
            <td><%= doctor.email %></td>
            <td><%= link_to t('watch_link'), doctor_path(doctor) %></td>
            <td><%= link_to t('calendar_link'), doctors_calendar_path(doctor) %></td>
            <td><%= link_to t('edit_link'), edit_doctor_path(doctor) %></td>
            <td><%= link_to t('delete_link'), doctor, method: :delete, data: { confirm: t('confirm_delete_message') } %></td>
          </tr>
      <% end %>
      </tbody>
    </table>


<% else %>
    <%= t('no_doctors_message') %>
<% end %>


<br>

<%= link_to t('submit_add_new_doctor'), new_doctor_path %>

app/views/doctors/new.html.erb
<fieldset class="smallForm">
  <legend class="formLegend"><h4><%= t('new_doctor_legend') %></h4></legend>

  <% if @doctor.errors.any? %>
      <div id="error_explanation" >
        <h4><%= pluralize(@doctor.errors.count, "error" ) %>
          Was found during validation, please fix them to continue:</h4>
        <ul>
          <% @doctor.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
  <% end %>

  <%= simple_form_for @doctor, :html => { :class => 'form-horizontal' } do |f| %>
      <%= f.input :name, label: t('name_header') %>
      <%= f.input :email, label: t('email_header')  %>
      <%= f.input :password, label: t('password_label') %>
      <%= f.input :password_confirmation, label: t('confirm_password_label') %>
      <br />
      <center>
        <%= f.button :submit, t('submit_new_doctor') %> &nbsp&nbsp&nbsp  <%= link_to t('go_back_to_doctors_link'), doctors_path %>
      </center>
  <% end %>



</fieldset>

app/views/doctors/show.html.erb
<fieldset class="smallForm">
  <legend class="formLegend"><h4><%= t('show_doctor_legend') %></h4></legend>
  <table class="table table-striped">
    <tr>
      <td>
        <%= t('name_header') %>
      </td>
      <td>
        <%= @doctor.name %>
      </td>
    </tr>
    <tr>
      <td>
        <%= t('email_header') %>
      </td>
      <td>
        <%= @doctor.email %>
      </td>
    </tr>
    <tr>
      <td colspan="2">
        <%= link_to t('go_back_to_doctors_link'), doctors_path %>
      </td>
    </tr>
  </table>

  <br />

  <!--TODO:Add calendar-->

  <br />


</fieldset>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MedicalProject</title>
  <%= stylesheet_link_tag  "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="wrapper">

  <!-- Title -->
  <div class="title">
    <div class="title-top">
      <div class="title-left">
        <div class="title-right">
          <div class="title-bottom">
            <div class="title-top-left">
              <div class="title-bottom-left">
                <div class="title-top-right">
                  <div class="title-bottom-right">
                    <h1><a href="/doctors/sign_in" title=<%= t('title_link') %>> <%= t('title_html') %></a></h1>

                    <p><%= t('title_p') %></p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- Title end -->

  <hr class="noscreen"/>

  <div class="content">

    <div class="column-left">
      <%if doctor_signed_in?%>
          <div class="smallForm">
            <p><%= t('entered_like') %> <%= current_doctor.name %></p>
            <br />
            <%= button_to t('leave'), destroy_doctor_session_path, method: :delete, :class=>"btn"  %>
          </div>
      <% end %>


      <h3><%= t('menu') %></h3>
      <a href="#skip-menu" class="hidden"></a>
      <ul class="menu">

        </li>
        <li><a href="/"> <%= t('main') %> </a></li>
        <li><a href="/patients/new"> <%= t('make_appointment') %> </a></li>
        <%if doctor_signed_in?%>
            <li><a href="/doctors"> <%= t('doctors_list_layout') %> </a></li>
        <% end %>
        <!--TODO:Disactivated because page is not ready yet-->
        <li><a href="/" onclick="return false" class="active"> О нас </a></li>

      </ul>
    </div>

    <div id="skip-menu"></div>
    <div class="column-right">
      <div class="box">
        <div class="box-top"></div>
        <div class="box-in">

          <%= yield %>

        </div>
      </div>

      <div class="box-bottom">

        <hr class="noscreen"/>

        <div class="footer-info-left"><a href="https://github.com/VladislavPovedyuk/MedicalProject"
                                         target="blank">Developers Team</a>, 2014.
        </div>

      </div>

      <div class="cleaner">&nbsp;</div>
    </div>
  </div>

</div>
</body>
</html>

app/views/meetings/edit.html.erb
<% if notice %>
    <p id="notice" ><%= notice %></p>
<% end %>

<fieldset class="smallForm" style="margin-right: 15%; margin-left: 15%;">
  <legend class="formLegend"><h4><%= t('meeting_edit_legend') %></h4></legend>

  <%= simple_form_for @meeting, method: :patch, :html => { :class => 'form-vertical' } do |f| %>
      <h5><%= t('doctor_label') %> <%= @doctor_name %></h5>
      <h5><%= t('patient_label') %> <%= @patient_name %></h5>
      <%= f.input :time_start, label: t('start_header'), :input_html => {:style => 'width: 100px'} %>
      <%= f.input :time_end, label: t('end_header') , :input_html => {:style => 'width: 100px'} %>
      <br />
      <center>
        <%= f.button :submit, t('submit_calendar') %> &nbsp&nbsp&nbsp <%= link_to t('go_back_to_calendar_link'), doctors_calendar_path(@meeting.doctor_id) %>
      </center>

  <% end %>



</fieldset>

app/views/patients/index.html.erb
<%= t('welcome_html') %>

app/views/patients/new.html.erb
<% if notice %>
    <p id="notice" ><%= notice %></p>
<% end %>

<fieldset class="smallForm">
  <legend class="formLegend"><h4><%= t('new_patient_legend') %></h4></legend>

  <% if @patient.errors.any? %>
      <div id="error_explanation" >
        <h4><%= pluralize(@patient.errors.count, "error" ) %>
          Was found during validation, please fix them to continue:</h4>
        <ul>
          <% @patient.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
  <% end %>

  <% if alert %>
      <div id="error_explanation" >
        <ul>
            <li><p id="alert" ><%= alert %></p></li>
        </ul>
      </div>
  <% end %>

    <%= simple_form_for @patient, :html => { :class => 'form-horizontal' } do |f| %>
        <%= f.input :name, label: t('name_label'), placeholder: t('name_placeholder') %>
        <%= f.input :skype, label: t('skype_label'), placeholder: t('skype_placeholder')  %>
        <%= f.input :tel, label: t('tel_label'), placeholder: t('tel_placeholder')  %>
        <%= f.input :age, label: t('age_label'), placeholder: t('age_placeholder'), collection: 18..50  %>
        <%= f.input :gender, :collection => ["М", "Ж"], :as => :radio_buttons, :label => t('gender_label') %>
        <%= simple_fields_for :doctors do |d|%>
            <%= d.input :id, collection: @doctors_names_list, :label => t('doctor_label') %>
        <% end %>
        <br />
        <center>
          <%= f.button :submit, t('submit_new_appointment') %>
        </center>
    <% end %>

</fieldset>

app/views/patients/show.erb
<fieldset class="smallForm">
  <legend class="formLegend"><h4>Информация о пациенте</h4></legend>
  <table class="table table-striped">
    <tr>
      <td>
        Имя :
      </td>
      <td>
        <%= @patient.name %>
      </td>
    </tr>
    <tr>
      <td>
        skype :
      </td>
      <td>
        <%= @patient.skype %>
      </td>
    </tr>
    <tr>
      <td>
        Возраст :
      </td>
      <td>
        <%= @patient.age %>
      </td>
    </tr>
    <tr>
      <td>
        Пол  :
      </td>
      <td>
        <%= @patient.gender %>
      </td>
    </tr>
    <tr>
      <td>
        Телефон :
      </td>
      <td>
        <%= @patient.tel %>
      </td>
    </tr>
    <tr>
      <td colspan="2">
        <a href="javascript:history.back();">Вернуться к списку встреч</a>
      </td>
    </tr>
  </table>
</fieldset>

app/views/patients/show.html.erb
<fieldset class="smallForm">
  <legend class="formLegend"><h4><%= t('show_patient_legend') %></h4></legend>
  <table class="table table-striped">
    <tr>
      <td>
        <%= t('name_label') %>
      </td>
      <td>
        <%= @patient.name %>
      </td>
    </tr>
    <tr>
      <td>
        <%= t('skype_label') %>
      </td>
      <td>
        <%= @patient.skype %>
      </td>
    </tr>
    <tr>
      <td>
        <%= t('age_label') %>
      </td>
      <td>
        <%= @patient.age %>
      </td>
    </tr>
    <tr>
      <td>
        <%= t('gender_label') %>
      </td>
      <td>
        <%= @patient.gender %>
      </td>
    </tr>
    <tr>
      <td>
        <%= t('tel_label') %>
      </td>
      <td>
        <%= @patient.tel %>
      </td>
    </tr>
    <tr>
      <td colspan="2">
        <a href="javascript:history.back();"><%= t('go_back_to_meetings_link') %></a>
      </td>
    </tr>
  </table>
</fieldset>